# This is a basic workflow to help you get started with Actions

name: build-readme

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:   # 触发时机
  push:    
  schedule:
    - cron:  '5 * * * *'  # 每5分钟运行一次
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
      pull-requests: write
      issues: write
      repository-projects: write
      contents: write
      pages: write
      id-token: write
concurrency:
      group: "pages"
      cancel-in-progress: false
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest   # 使用最新版ubuntu镜像 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout
      uses: actions/checkout@v4  
      
    - name: Setup Python  # 安装python环境 
      uses: actions/setup-python@v2

    - name: Install Python dependencies  # 安装python爬虫依赖包
      run: python -m pip install urllib3 lxml beautifulsoup4 requests

    - name: download list2.txt
      run: wget ogszzd.herokuapp.com/api.php?c=get_list_v1 -O list2.txt
      
    - name: download index.html
      run: wget szmj0.github.io -O index.html

    - name: Run python   # 生成新的README.md文件 
      run: python generateReadme.py and requests

    - name: Record time  
      run: echo `date` > date.log

    - name: Commit and push if changed   # 将README.md更新到仓库
      run: |
          git diff 
          git config --global user.email "x@1x1.io"
          git config --global user.name "1x1"
          git add -A
          git commit -m "Updated Readme" || exit 
          git push -f
